services:
    app-service:
        image: beaglepete/app-service
        restart: 'always'
        environment:
            AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost} # Use localhost as the default value
        ports:
            - '8001:8001'
        depends_on:
            auth-service:
                condition: service_started
    auth-service:
        image: beaglepete/auth-service
        restart: 'always'
        environment:
            JWT_SECRET: ${JWT_SECRET}
            DROPLET_IP: ${DROPLET_IP}
            DATABASE_URL: 'postgres://postgres:${POSTGRES_PASSWORD}@db:5432'
        ports:
            - '3000:3000' # expose port 3000 so that applications outside the container can connect to it
        depends_on:
            - db
    db:
        image: postgres:15.2-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
    redis:
        image: redis:7.0-alpine
        restart: always
        ports:
            - '6379:6379'

volumes:
    db:
        driver: local
